# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import config_pb2 as config__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManageAgentOpsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommands = channel.unary_unary(
                '/ManageAgentOps/ExecuteCommands',
                request_serializer=config__pb2.ExecuteCommandsRequest.SerializeToString,
                response_deserializer=config__pb2.ExecuteCommandsResponse.FromString,
                _registered_method=True)
        self.CreateFiles = channel.unary_unary(
                '/ManageAgentOps/CreateFiles',
                request_serializer=config__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=config__pb2.CreateFileResponse.FromString,
                _registered_method=True)
        self.ViewFile = channel.unary_unary(
                '/ManageAgentOps/ViewFile',
                request_serializer=config__pb2.ViewFileRequest.SerializeToString,
                response_deserializer=config__pb2.ViewFileResponse.FromString,
                _registered_method=True)


class ManageAgentOpsServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManageAgentOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommands,
                    request_deserializer=config__pb2.ExecuteCommandsRequest.FromString,
                    response_serializer=config__pb2.ExecuteCommandsResponse.SerializeToString,
            ),
            'CreateFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFiles,
                    request_deserializer=config__pb2.CreateFileRequest.FromString,
                    response_serializer=config__pb2.CreateFileResponse.SerializeToString,
            ),
            'ViewFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewFile,
                    request_deserializer=config__pb2.ViewFileRequest.FromString,
                    response_serializer=config__pb2.ViewFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ManageAgentOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ManageAgentOps', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManageAgentOps:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ManageAgentOps/ExecuteCommands',
            config__pb2.ExecuteCommandsRequest.SerializeToString,
            config__pb2.ExecuteCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ManageAgentOps/CreateFiles',
            config__pb2.CreateFileRequest.SerializeToString,
            config__pb2.CreateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ManageAgentOps/ViewFile',
            config__pb2.ViewFileRequest.SerializeToString,
            config__pb2.ViewFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
